name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.0.6
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  lottie:
  # services
  video_player: ^2.3.0
  http:
  get:
  wakelock:
  universal_html:
  youtube_explode_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/
