name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.1.5
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # services
  video_player: ^2.6.1
  http: ^0.13.6  
  get: ^4.6.5  
  wakelock: ^0.6.2 
  universal_html: ^2.2.3 
  youtube_explode_dart: ^1.12.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

screenshots:
  - description: Pod video player logo
    path: screenshots/logo.png