name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.1.0
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  lottie: ^1.3.0  
  # services
  video_player: ^2.4.5
  http: ^0.13.4  
  get: ^4.6.5  
  wakelock: ^0.6.1+2 
  universal_html: ^2.0.8 
  youtube_explode_dart: ^1.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/
