name: CI

on:
  push:
  pull_request:

jobs:
  check-format:
      name: Check format using flutter format
      runs-on: ubuntu-latest
      container: cirrusci/flutter:stable

      steps:
          uses: actions/checkout@v2
        - name: Check format
          run: flutter format --set-exit-if-changed .

  lint:
    name: Checking lints
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
        uses: actions/checkout@v2
      - name: Get dependencies 
        run: flutter pub get
      - name: Lint using flutter analyze
        run: flutter analyze
        